"""Point-in-time research-data boundaries for calibration pilots."""

from engine.research_data.contracts import (
    HistoricalFilingSource,
    HistoricalInputEnvelope,
    HistoricalPriceSource,
    HistoricalSecurityCandidate,
    HistoricalUniverseSnapshot,
    HistoricalUniverseSource,
    ResearchDataFailure,
    ResearchDataFailureReason,
    ResearchDataResult,
    SourceReference,
)
from engine.research_data.pilot import (
    M12B0PilotManifest,
    PilotAnchorResult,
    PilotVerdict,
    StressSetResult,
    load_pilot_manifest,
)
from engine.research_data.sampling import PilotSamplePlan, deterministic_sample
from engine.research_data.tiingo import (
    TiingoActionValidation,
    TiingoAdjustmentEvidence,
    TiingoAuthenticationError,
    TiingoClient,
    TiingoClientSettings,
    TiingoEODObservation,
    TiingoEODSeries,
    TiingoHistoricalPriceSource,
    TiingoMalformedResponseError,
    TiingoMetadata,
    TiingoMissingTokenError,
    TiingoProviderError,
    TiingoRateLimitError,
    TiingoSearchResult,
    TiingoTransportResponse,
    tiingo_cache_key,
    tiingo_to_price_snapshots,
    validate_tiingo_dividend_adjustment,
    validate_tiingo_split_adjustment,
)

__all__ = [
    "HistoricalFilingSource",
    "HistoricalInputEnvelope",
    "HistoricalPriceSource",
    "HistoricalSecurityCandidate",
    "HistoricalUniverseSnapshot",
    "HistoricalUniverseSource",
    "M12B0PilotManifest",
    "PilotAnchorResult",
    "PilotSamplePlan",
    "PilotVerdict",
    "ResearchDataFailure",
    "ResearchDataFailureReason",
    "ResearchDataResult",
    "SourceReference",
    "StressSetResult",
    "TiingoActionValidation",
    "TiingoAdjustmentEvidence",
    "TiingoAuthenticationError",
    "TiingoClient",
    "TiingoClientSettings",
    "TiingoEODObservation",
    "TiingoEODSeries",
    "TiingoHistoricalPriceSource",
    "TiingoMalformedResponseError",
    "TiingoMetadata",
    "TiingoMissingTokenError",
    "TiingoProviderError",
    "TiingoRateLimitError",
    "TiingoSearchResult",
    "TiingoTransportResponse",
    "deterministic_sample",
    "load_pilot_manifest",
    "tiingo_cache_key",
    "tiingo_to_price_snapshots",
    "validate_tiingo_dividend_adjustment",
    "validate_tiingo_split_adjustment",
]
