"""create persistence phase1 schema

Revision ID: 20260904_0001
Revises: None
Create Date: 2026-09-04 18:40:36.391480
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260904_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('canonical_name', sa.String(length=250), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('source_references',
    sa.Column('source_reference_id', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_reference_id')
    )
    op.create_table('instruments',
    sa.Column('instrument_id', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('security_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary_listing', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('instrument_id'),
    sa.UniqueConstraint('exchange', 'ticker', name='uq_instrument_exchange_ticker')
    )
    op.create_index(op.f('ix_instruments_company_id'), 'instruments', ['company_id'], unique=False)
    op.create_table('analysis_snapshots',
    sa.Column('snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('instrument_id', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case', sa.String(length=80), nullable=False),
    sa.Column('case_version', sa.String(length=80), nullable=False),
    sa.Column('analysis_version', sa.String(length=80), nullable=False),
    sa.Column('price_reference_id', sa.String(length=120), nullable=True),
    sa.Column('supersedes_snapshot_id', sa.String(length=120), nullable=True),
    sa.Column('revision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.ForeignKeyConstraint(['supersedes_snapshot_id'], ['analysis_snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_analysis_snapshots_as_of'), 'analysis_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_analysis_snapshots_company_id'), 'analysis_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_analysis_snapshots_instrument_id'), 'analysis_snapshots', ['instrument_id'], unique=False)
    op.create_table('thesis_definitions',
    sa.Column('thesis_definition_row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.String(length=120), nullable=False),
    sa.Column('thesis_version', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=True),
    sa.Column('instrument_id', sa.String(length=100), nullable=True),
    sa.Column('case', sa.String(length=80), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('core_thesis', sa.Text(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('why_this_company', sa.Text(), nullable=True),
    sa.Column('failure_modes', sa.JSON(), nullable=False),
    sa.Column('kpi_set_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('thesis_definition_row_id'),
    sa.UniqueConstraint('thesis_id', 'thesis_version', name='uq_thesis_version')
    )
    op.create_table('tracking_kpi_definitions',
    sa.Column('tracking_kpi_definition_row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kpi_definition_id', sa.String(length=120), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=True),
    sa.Column('instrument_id', sa.String(length=100), nullable=True),
    sa.Column('thesis_id', sa.String(length=120), nullable=False),
    sa.Column('thesis_version', sa.Integer(), nullable=False),
    sa.Column('kpi_set_version', sa.Integer(), nullable=False),
    sa.Column('kpi_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('primary_flag', sa.Boolean(), nullable=False),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('frequency', sa.String(length=60), nullable=True),
    sa.Column('source_type', sa.String(length=120), nullable=False),
    sa.Column('breaker_rule', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('tracking_kpi_definition_row_id'),
    sa.UniqueConstraint('kpi_definition_id', 'kpi_set_version', name='uq_kpi_definition_version')
    )
    op.create_table('valuation_assumptions',
    sa.Column('valuation_assumption_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assumption_set_id', sa.String(length=120), nullable=False),
    sa.Column('assumption_version', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=True),
    sa.Column('instrument_id', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('required_return', sa.Float(), nullable=False),
    sa.Column('terminal_stage', sa.String(length=40), nullable=False),
    sa.Column('primary_metric', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.String(length=40), nullable=False),
    sa.Column('plausible_growth_low', sa.Float(), nullable=True),
    sa.Column('plausible_growth_high', sa.Float(), nullable=True),
    sa.Column('expected_dilution', sa.Float(), nullable=True),
    sa.Column('target_gross_margin', sa.Float(), nullable=True),
    sa.Column('target_operating_margin', sa.Float(), nullable=True),
    sa.Column('terminal_net_debt', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('valuation_assumption_id'),
    sa.UniqueConstraint('assumption_set_id', 'assumption_version', name='uq_valuation_assumption_version')
    )
    op.create_table('current_trend_snapshots',
    sa.Column('snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('analysis_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('overall_state', sa.String(length=40), nullable=False),
    sa.Column('engine_version', sa.String(length=80), nullable=False),
    sa.Column('comparison_period', sa.Date(), nullable=False),
    sa.Column('funding_stress', sa.Boolean(), nullable=False),
    sa.Column('commercial_inflection', sa.Boolean(), nullable=False),
    sa.Column('commercial_deterioration', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_snapshot_id'], ['analysis_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('analysis_snapshot_id')
    )
    op.create_table('exit_multiple_evidence',
    sa.Column('evidence_id', sa.String(length=180), nullable=False),
    sa.Column('valuation_assumption_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valuation_metric', sa.String(length=40), nullable=False),
    sa.Column('band', sa.String(length=40), nullable=False),
    sa.Column('observed_low', sa.Float(), nullable=True),
    sa.Column('observed_high', sa.Float(), nullable=True),
    sa.Column('reference_value', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['valuation_assumption_id'], ['valuation_assumptions.valuation_assumption_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id'),
    sa.UniqueConstraint('valuation_assumption_id', 'band', name='uq_exit_evidence_band')
    )
    op.create_table('investment_grade_snapshots',
    sa.Column('snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('analysis_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('initial_grade', sa.String(length=20), nullable=False),
    sa.Column('final_grade', sa.String(length=20), nullable=False),
    sa.Column('engine_version', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_snapshot_id'], ['analysis_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('analysis_snapshot_id')
    )
    op.create_table('material_events',
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('instrument_id', sa.String(length=100), nullable=False),
    sa.Column('previous_snapshot_id', sa.String(length=120), nullable=True),
    sa.Column('current_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('current_value', sa.JSON(), nullable=True),
    sa.Column('reason_type', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['analysis_snapshots.snapshot_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['analysis_snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('narrative_snapshots',
    sa.Column('snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('analysis_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('narrative_version', sa.String(length=80), nullable=False),
    sa.Column('thesis_id', sa.String(length=120), nullable=False),
    sa.Column('thesis_version', sa.Integer(), nullable=False),
    sa.Column('kpi_set_version', sa.Integer(), nullable=False),
    sa.Column('overall_state', sa.String(length=40), nullable=False),
    sa.Column('narrative_gate', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_snapshot_id'], ['analysis_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('analysis_snapshot_id')
    )
    op.create_table('price_snapshots',
    sa.Column('price_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('instrument_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('enterprise_value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=250), nullable=False),
    sa.Column('price_type', sa.String(length=30), nullable=False),
    sa.Column('analysis_snapshot_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_price_positive'),
    sa.ForeignKeyConstraint(['analysis_snapshot_id'], ['analysis_snapshots.snapshot_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('price_snapshot_id'),
    sa.UniqueConstraint('instrument_id', 'timestamp', 'source', 'price_type', name='uq_price_import_key')
    )
    op.create_index(op.f('ix_price_snapshots_instrument_id'), 'price_snapshots', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_timestamp'), 'price_snapshots', ['timestamp'], unique=False)
    op.create_table('quant_snapshots',
    sa.Column('snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('analysis_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('engine_version', sa.String(length=80), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('raw_grade', sa.String(length=20), nullable=True),
    sa.Column('final_grade', sa.String(length=20), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('resolution_state', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_snapshot_id'], ['analysis_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('analysis_snapshot_id')
    )
    op.create_table('thesis_status_snapshots',
    sa.Column('snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('analysis_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('thesis_id', sa.String(length=120), nullable=False),
    sa.Column('thesis_version', sa.Integer(), nullable=False),
    sa.Column('kpi_set_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('breaker_triggered', sa.Boolean(), nullable=False),
    sa.Column('observation_ids', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.CheckConstraint("lower(status) <> 'stable'", name='ck_thesis_status_not_stable'),
    sa.ForeignKeyConstraint(['analysis_snapshot_id'], ['analysis_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('analysis_snapshot_id')
    )
    op.create_table('tracking_kpi_observations',
    sa.Column('observation_id', sa.String(length=120), nullable=False),
    sa.Column('kpi_definition_id', sa.String(length=120), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=True),
    sa.Column('instrument_id', sa.String(length=100), nullable=True),
    sa.Column('analysis_snapshot_id', sa.String(length=120), nullable=True),
    sa.Column('kpi_key', sa.String(length=120), nullable=False),
    sa.Column('thesis_version', sa.Integer(), nullable=False),
    sa.Column('kpi_set_version', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_state', sa.String(length=30), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_snapshot_id'], ['analysis_snapshots.snapshot_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('valuation_snapshots',
    sa.Column('snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('analysis_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('assumption_set_id', sa.String(length=120), nullable=False),
    sa.Column('assumption_version', sa.Integer(), nullable=False),
    sa.Column('required_return', sa.Float(), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('terminal_stage', sa.String(length=40), nullable=False),
    sa.Column('expectation_gap', sa.String(length=40), nullable=False),
    sa.Column('bear_value', sa.Float(), nullable=True),
    sa.Column('base_value', sa.Float(), nullable=True),
    sa.Column('bull_value', sa.Float(), nullable=True),
    sa.Column('downside_severity', sa.String(length=80), nullable=True),
    sa.Column('upside_optionality', sa.String(length=80), nullable=True),
    sa.Column('asymmetry_type', sa.String(length=40), nullable=False),
    sa.Column('valuation_confidence', sa.String(length=40), nullable=False),
    sa.Column('market_price_reference', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_snapshot_id'], ['analysis_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assumption_set_id', 'assumption_version'], ['valuation_assumptions.assumption_set_id', 'valuation_assumptions.assumption_version'], name='fk_valuation_snapshot_assumption_version'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('analysis_snapshot_id')
    )
    op.create_table('current_trend_signals',
    sa.Column('current_trend_signal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('current_trend_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('signal_key', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_trend_snapshot_id'], ['current_trend_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('current_trend_signal_id'),
    sa.UniqueConstraint('current_trend_snapshot_id', 'signal_key', name='uq_current_signal_key')
    )
    op.create_table('investment_grade_adjustments',
    sa.Column('investment_grade_adjustment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investment_grade_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=30), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('maximum_grade', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['investment_grade_snapshot_id'], ['investment_grade_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investment_grade_adjustment_id'),
    sa.UniqueConstraint('investment_grade_snapshot_id', 'sequence', name='uq_grade_adjustment_sequence')
    )
    op.create_table('metric_results',
    sa.Column('metric_result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quant_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=150), nullable=False),
    sa.Column('raw_value', sa.JSON(), nullable=True),
    sa.Column('normalized_value', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('resolution_state', sa.String(length=30), nullable=False),
    sa.Column('source_period', sa.Date(), nullable=False),
    sa.Column('calculation_version', sa.String(length=80), nullable=False),
    sa.Column('normalization_notes', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['quant_snapshot_id'], ['quant_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_result_id'),
    sa.UniqueConstraint('quant_snapshot_id', 'metric_key', name='uq_metric_quant_key')
    )
    op.create_index(op.f('ix_metric_results_quant_snapshot_id'), 'metric_results', ['quant_snapshot_id'], unique=False)
    op.create_table('narrative_assessments',
    sa.Column('narrative_assessment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('narrative_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['narrative_snapshot_id'], ['narrative_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('narrative_assessment_id'),
    sa.UniqueConstraint('narrative_snapshot_id', 'dimension', name='uq_narrative_dimension')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('narrative_assessments')
    op.drop_index(op.f('ix_metric_results_quant_snapshot_id'), table_name='metric_results')
    op.drop_table('metric_results')
    op.drop_table('investment_grade_adjustments')
    op.drop_table('current_trend_signals')
    op.drop_table('valuation_snapshots')
    op.drop_table('tracking_kpi_observations')
    op.drop_table('thesis_status_snapshots')
    op.drop_table('quant_snapshots')
    op.drop_index(op.f('ix_price_snapshots_timestamp'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_instrument_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('narrative_snapshots')
    op.drop_table('material_events')
    op.drop_table('investment_grade_snapshots')
    op.drop_table('exit_multiple_evidence')
    op.drop_table('current_trend_snapshots')
    op.drop_table('valuation_assumptions')
    op.drop_table('tracking_kpi_definitions')
    op.drop_table('thesis_definitions')
    op.drop_index(op.f('ix_analysis_snapshots_instrument_id'), table_name='analysis_snapshots')
    op.drop_index(op.f('ix_analysis_snapshots_company_id'), table_name='analysis_snapshots')
    op.drop_index(op.f('ix_analysis_snapshots_as_of'), table_name='analysis_snapshots')
    op.drop_table('analysis_snapshots')
    op.drop_index(op.f('ix_instruments_company_id'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('source_references')
    op.drop_table('companies')
    # ### end Alembic commands ###
