"""add performance phase1 schema

Revision ID: 20260904_0002
Revises: 20260904_0001
Create Date: 2026-09-04 19:46:36.681617
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260904_0002'
down_revision: Union[str, Sequence[str], None] = '20260904_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_assignments',
    sa.Column('benchmark_assignment_row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.String(length=120), nullable=False),
    sa.Column('assignment_version', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(length=100), nullable=False),
    sa.Column('benchmark_instrument_id', sa.String(length=100), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_instrument_id'], ['instruments.instrument_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('benchmark_assignment_row_id'),
    sa.UniqueConstraint('assignment_id', 'assignment_version', name='uq_benchmark_assignment_version')
    )
    op.create_index(op.f('ix_benchmark_assignments_instrument_id'), 'benchmark_assignments', ['instrument_id'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('performance_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('analysis_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('instrument_id', sa.String(length=100), nullable=False),
    sa.Column('evaluation_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_type', sa.String(length=40), nullable=False),
    sa.Column('price_basis', sa.String(length=40), nullable=False),
    sa.Column('start_price_snapshot_id', sa.String(length=120), nullable=True),
    sa.Column('start_price', sa.Float(), nullable=True),
    sa.Column('benchmark_assignment_id', sa.String(length=120), nullable=True),
    sa.Column('benchmark_assignment_version', sa.Integer(), nullable=True),
    sa.Column('benchmark_instrument_id', sa.String(length=100), nullable=True),
    sa.Column('benchmark_return_type', sa.String(length=40), nullable=True),
    sa.Column('benchmark_price_basis', sa.String(length=40), nullable=True),
    sa.Column('benchmark_start_price_snapshot_id', sa.String(length=120), nullable=True),
    sa.Column('benchmark_start_price', sa.Float(), nullable=True),
    sa.Column('return_since_analysis', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('mdd_coverage_status', sa.String(length=30), nullable=False),
    sa.Column('mdd_observation_count', sa.Integer(), nullable=False),
    sa.Column('mdd_first_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mdd_last_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mdd_maximum_observed_gap_days', sa.Integer(), nullable=True),
    sa.Column('resolution_state', sa.String(length=30), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('calculation_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_snapshot_id'], ['analysis_snapshots.snapshot_id'], ),
    sa.ForeignKeyConstraint(['benchmark_assignment_id', 'benchmark_assignment_version'], ['benchmark_assignments.assignment_id', 'benchmark_assignments.assignment_version'], name='fk_performance_benchmark_assignment'),
    sa.ForeignKeyConstraint(['benchmark_instrument_id'], ['instruments.instrument_id'], ),
    sa.ForeignKeyConstraint(['benchmark_start_price_snapshot_id'], ['price_snapshots.price_snapshot_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.ForeignKeyConstraint(['start_price_snapshot_id'], ['price_snapshots.price_snapshot_id'], ),
    sa.PrimaryKeyConstraint('performance_snapshot_id')
    )
    op.create_index(op.f('ix_performance_snapshots_analysis_snapshot_id'), 'performance_snapshots', ['analysis_snapshot_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_evaluation_as_of'), 'performance_snapshots', ['evaluation_as_of'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_instrument_id'), 'performance_snapshots', ['instrument_id'], unique=False)
    op.create_table('performance_horizons',
    sa.Column('performance_horizon_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('performance_snapshot_id', sa.String(length=120), nullable=False),
    sa.Column('horizon', sa.String(length=10), nullable=False),
    sa.Column('resolution_state', sa.String(length=30), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('end_price_snapshot_id', sa.String(length=120), nullable=True),
    sa.Column('end_price', sa.Float(), nullable=True),
    sa.Column('stock_return', sa.Float(), nullable=True),
    sa.Column('stock_start_effective_date', sa.Date(), nullable=True),
    sa.Column('stock_end_effective_date', sa.Date(), nullable=True),
    sa.Column('benchmark_end_price_snapshot_id', sa.String(length=120), nullable=True),
    sa.Column('benchmark_end_price', sa.Float(), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('benchmark_return_type', sa.String(length=40), nullable=True),
    sa.Column('benchmark_start_effective_date', sa.Date(), nullable=True),
    sa.Column('benchmark_end_effective_date', sa.Date(), nullable=True),
    sa.Column('alpha_state', sa.String(length=30), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('alpha_unresolved_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_end_price_snapshot_id'], ['price_snapshots.price_snapshot_id'], ),
    sa.ForeignKeyConstraint(['end_price_snapshot_id'], ['price_snapshots.price_snapshot_id'], ),
    sa.ForeignKeyConstraint(['performance_snapshot_id'], ['performance_snapshots.performance_snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('performance_horizon_id'),
    sa.UniqueConstraint('performance_snapshot_id', 'horizon', name='uq_performance_horizon')
    )
    op.create_index(op.f('ix_performance_horizons_performance_snapshot_id'), 'performance_horizons', ['performance_snapshot_id'], unique=False)
    with op.batch_alter_table('price_snapshots') as batch_op:
        batch_op.add_column(sa.Column('price_basis', sa.String(length=40), server_default='raw', nullable=False))
        batch_op.add_column(sa.Column('adjustment_version', sa.String(length=100), server_default='', nullable=False))
        batch_op.add_column(sa.Column('provider_reference', sa.Text(), nullable=True))
        batch_op.drop_constraint('uq_price_import_key', type_='unique')
        batch_op.create_unique_constraint('uq_price_import_key', ['instrument_id', 'timestamp', 'source', 'price_type', 'price_basis', 'adjustment_version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshots') as batch_op:
        batch_op.drop_constraint('uq_price_import_key', type_='unique')
        batch_op.create_unique_constraint('uq_price_import_key', ['instrument_id', 'timestamp', 'source', 'price_type'])
        batch_op.drop_column('provider_reference')
        batch_op.drop_column('adjustment_version')
        batch_op.drop_column('price_basis')
    op.drop_index(op.f('ix_performance_horizons_performance_snapshot_id'), table_name='performance_horizons')
    op.drop_table('performance_horizons')
    op.drop_index(op.f('ix_performance_snapshots_instrument_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_evaluation_as_of'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_analysis_snapshot_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_benchmark_assignments_instrument_id'), table_name='benchmark_assignments')
    op.drop_table('benchmark_assignments')
    # ### end Alembic commands ###
